### ISSUE TITLE
Host it somewhere (eg on GitHub pages)

### ISSUE THREAD

**Issue by Naereen** [jbdo99/BetterOCaml#2]
Hello there @jbdo99,

Thanks for sharing your tool.  It seems interesting, thanks!

Could you host it somewhere online, so everybody can try it and use it if they want?

Using GitHub pages, it shouldn't be too hard.
Thanks in advance! -- @Naereen

**Comment by jbdo99** [comment]
Yes of course, https://betterocaml.ml

**Comment by jbdo99** [comment]
The local download is not updated but the online version yes

**Comment by Naereen** [comment]
Who, awesome!
It's nice to have a second alternative, if [TryOCaml](https://try.ocamlpro.com/) is down.

I just discovered that recent TryOCaml has inline support for errors, and it's brilliant for beginners, so I'll keep using TryOCaml for my teaching activities.
![Capture d’écran de 2021-02-14 19-32-38](https://user-images.githubusercontent.com/11994719/107885622-b3f5a900-6efb-11eb-9e21-5054c0646814.png)

**Comment by Naereen** [comment]
Maybe you could had a link from https://betterocaml.ml/ to https://github.com/jbdo99/BetterOCaml/ ?

**Comment by Naereen** [comment]
I also took the liberty of hosting a copy on [my website](https://perso.crans.org/besson/publis/BetterOCaml/) (with no incoming link, so it's meant for private use), just in case https://betterocaml.ml/ is unreachable.

**Comment by Naereen** [comment]
> Maybe you could had a link from https://betterocaml.ml/ to https://github.com/jbdo99/BetterOCaml/ ?
I meant a link from the homepage, not from the editor, as there is one from the menu :wrench:.

**Comment by jbdo99** [comment]
It's done, thank you for your interest in the project.
