### ISSUE TITLE
Add a small (<2min) GIF showing all the features of BetterOCaml

### ISSUE THREAD

**Issue by Naereen** [jbdo99/BetterOCaml#20]
I'll do it!

**Comment by Naereen** [comment]
About 2 minutes, ~9 Mo (GIF are heavy for this...)
![demo-opt](https://user-images.githubusercontent.com/11994719/109438223-484a2a80-7a29-11eb-9de0-48889746d59c.gif)

**Comment by Naereen** [comment]
And here is one showing the installation as PWA:

**Comment by Naereen** [comment]
The easiest way to use these GIF in the README should be to just add a link to this issue, like this:

```markdown
Two short video show how to use all the features of BetterOCaml [in this page](https://github.com/jbdo99/BetterOCaml/issues/20).
```

Two short video show how to use all the features of BetterOCaml [in this page](https://github.com/jbdo99/BetterOCaml/issues/20).

**Comment by jbdo99** [comment]
Done 👍 #38
