### ISSUE TITLE
Add a small badge to advertize about the quality of the progressive web app

### ISSUE THREAD

**Issue by Naereen** [jbdo99/BetterOCaml#25]
Hi there,
Using this repository <https://github.com/ankurparihar/readme-pagespeed-insights>, this badge shows that Google Pagespeed Insights (<https://developers.google.com/speed/pagespeed/insights/?url=https://betterocaml.ml/>) gives a pretty good summary of the quality of the website and its progressive web app:
![betterocaml ml](https://user-images.githubusercontent.com/11994719/112282433-694c1700-8c87-11eb-9d0e-99f23f00f9dd.png)
The last badge is especially useful, as it advertises about the PWA being ready and installable.
I can add it the README.md if you want.

**Comment by Naereen** [comment]
I had to do a screenshot of this page <https://pagespeed-insights.herokuapp.com/?url=https://betterocaml.ml/> instead of downloading the SVG, it wasn't correctly formatted.

**Comment by jbdo99** [comment]
Thanks, i added the the result of my last commit (with some improvements on SEO)  at the end of the README. They suggest on the repository to download the svg because it takes time to render

![pwa_performance_2503](https://user-images.githubusercontent.com/10222041/112509800-1a8aa400-8d91-11eb-8d62-04ff7dd4487a.png)

**Comment by Naereen** [comment]
Woo, congrats for the improvements!

**Comment by Naereen** [comment]
The screenshot included in the README has so vertical space which just contain black space, but it's not important.
Also, the image could link to https://pagespeed-insights.herokuapp.com/?url=https://betterocaml.ml/ ?
