### ISSUE TITLE
Multiple version of the Ocaml Toplevel

### ISSUE THREAD

**Issue by jbdo99** [jbdo99/BetterOCaml#33]
A great idea from [Naereen](https://github.com/Naereen), add the possibility to choose the ocaml version with the url (something like this : ` https://betterocaml.ml/?version=4.07`)

Need to add compilation for these versions in GA (see [issue #32](https://github.com/jbdo99/BetterOCaml/issues/32))

**Comment by jbdo99** [comment]
Done.
Todo next :
-UI interface
-PWA cache support ?
-CI

**Comment by Naereen** [comment]
I don't think it is necessary to add a UI button for this.
Document this small feature on the README, it will be enough for « power users », who I guess will be the only users interested in this feature!

**Comment by jbdo99** [comment]
Done [#35](https://github.com/jbdo99/BetterOCaml/pull/35)

**Comment by Naereen** [comment]
Great new feature! @jbdo99 :clap:!

However, I was not able to find any mention of it in the README?

**Comment by jbdo99** [comment]
Done #38 👍
