### ISSUE TITLE
Add some basic documentation: what it is, how to use it, what software are included etc?

### ISSUE THREAD

**Issue by Naereen** [jbdo99/BetterOCaml#4]
Hello again,
Could you add a `README.md` file explaining what is this project, how to use it, what software are included etc?
Regards, -- @Naereen

**Comment by jbdo99** [comment]
Work in progress :)

**Comment by jbdo99** [comment]
@Naereen et bonjour de la mp*1 de Thiers ;)

**Comment by Naereen** [comment]
Hoho, le monde est petit, j'étais en MP*1 à Thiers en 2010/2011 !

**Comment by BastouP411** [comment]
@Naereen Héhé oui ! Vous aviez Mme Borel et Henriet ?

**Comment by Naereen** [comment]
> Work in progress :)
Don't hesitate to ping me here, when a README.md file will be added, so I can give advice if needed.

I would also suggest writing a Makefile (or equivalent) so building the compiled version can be easily reproduced.

**Comment by Naereen** [comment]
> @Naereen Héhé oui ! Vous aviez Mme Borel et Henriet ?

@BastouP411 @jbdo99 vous êtes deux camarades ? Vous êtes actuellement en MP*1 ?
J'ai eu Mme Borel en effet, mais Mr Alfaro en physique ! (et je ne me rappelle plus des noms des autres profs, oups)

**Comment by BastouP411** [comment]
@Naereen Oui on est tous les 2 en MP*1.
Mme Borel est partie à la retraite l'année dernière.
On a:
Mme Amiel en français
M Reissman/Noyer en option informatique
Mme Beteille en Anglais

Et moi j'étais en MPSI2 et j'avais Mme Lhopital en physique et M Dakhli en maths.
Si ça vous dit quelque chose.

**Comment by Naereen** [comment]
Trop bien, je suis content de savoir des taupin-e-s actif-ve-s sur GitHub :crown: !
Je ne connais pas les autres profs de MP*, en particulier pas ceux d'option informatique (mais comme je vais probablement devenir prof d'info en prépa bientôt, je les contacterai un jour ou l'autre !).
J'ai eu la même équipe en MPSI 2 :+1: !

Si vous êtes encore présent physiquement au lycée, svp transmettez mon bon souvenir à l'oral aux profs de MPSI 2, ils et elles se rappellent de moi je pense :wink: ! (Lilian Besson, 2009/2010)

**Comment by BastouP411** [comment]
@Naereen Oui, on est encore en présentiel. Du coup ce sera sera fait pour M Dakhli, mais Mme Lhopital est partie à la retraite fin 2019. On était sa dernière classe ^^

**Comment by Naereen** [comment]
Si par hasard vous avez son adresse email, je la veux bien je ne l'ai plus (mais pas par message ici, ça ne doit pas être public, svp faites moi un mail à `naereen at crans.org`)

**Comment by BastouP411** [comment]
C'est bon je vous l'ai envoyée :)

**Comment by jbdo99** [comment]
@Naereen I posted a first version of a correct readme and made a big update :)

**Comment by Naereen** [comment]
@jbdo99 Really nice update, great job!

**Comment by Naereen** [comment]
@jbdo99 this issue could be closed, I guess?
