### ISSUE TITLE
Change the description (GitHub meta data) to say: web IDE + offline-ready

### ISSUE THREAD

**Issue by Naereen** [jbdo99/BetterOCaml#8]
Hi there again,

I just realized that the description was a little bit misleading
> An efficient, intuitive and cross-platform Ocaml IDE 

Maybe it could be changed to
> A small but efficient, intuitive and responsive OCaml IDE right in your browser! Ships OCaml v4.08.1, interpreter by your browser (so it works offline!), compiled with js_of_ocaml.

It's longer, but it makes things clearer:
- "small" : it's a very nice web editor, but calling it a "IDE" when it has just edit/save and run is a bit too much ;
- "responsive": inform users that it should work well on smartphone (note: it's not yet good for me, but I'm finishing a modification of the page and its style to have a better experience on small screens) ;

- "right in your browser": very very important to explain right in the description that it's an in browser IDE;
- "Ships OCaml v4.08": this can help promote the fact that it's recent, when compared to other pages that have older OCaml versions ([thinking of mine](https://perso.crans.org/besson/ocaml.fr.html) with OCaml 4.01);
- "interpreter by your browser": it's an awesome feature!
- "(so it works offline!)" : it doesn't work yet on mobile phones I think (or at least, not mine), but it should work fine on modern desktop/laptop browser,
- "compiled with js_of_ocaml": that's not mandatory.

Of course this is a just a suggestion, feel free to pick only some of the items I suggest to add.
But it should at least make these points clear :ok
!

**Comment by Naereen** [comment]
Great thanks for the update.

I will applaud if you obtain autocompletion. But that's not vital.
It's quite hard to implement correctly...

**Comment by Naereen** [comment]
I'm trying to get my head around service workers and app manifest... to make it installable as offline app on mobiles.

**Comment by jbdo99** [comment]
I've created a web dev branch on the repo and invite you as collaborator, so it's easier to work and make some modification
Also if you want, I have also created a mini [discord server](https://discord.gg/eJpKVzekDh) if you :)

**Comment by Naereen** [comment]
I'll see in a few days.

This morning I managed to write a Progressive Web App (PWA) manifest JSON file (extending the one that I found, afterward, in the src/icon folder). I successfully installed the website as a "native PWA" on my Android phone.
It works, but... so many things are not perfect!

- no offline support - [service workers](https://mykmelez.github.io/offline-web-apps-on-github-pages/?full#service-workers) are required for this!
- despite my CSS hack to make it more responsive, it's not very easy to use;
- lots of tiny things don't work as expected on CodeMirror, like copy-pasting etc. I wrote a ~12 lines example, and I was already tired of it... the only known native OCaml for Android, [OCaml Toplevel for Android](https://play.google.com/store/apps/details?id=fr.vernoux.ocaml) (2011, OCaml v3.12.0) is 10-year-old but so smooth and easy to use.
- the save and setting buttons become quickly hidden?
- interpreting a sentence makes the virtual keyboard hide and come back quickly, cluttering the display;
- the editor highlights the current line/statement that will be executed, and that's perfect. On desktop, it displays nicely, on my phone it removed the syntax highlighting of the editor, as soon as I had more than one statement.

I'll stop there...
This is not meant to be aggressive, just to give some feedback about my experiments.
So far, if I were to teach using OCaml, I'll still be recommending to use [OCaml Toplevel for Android](https://play.google.com/store/apps/details?id=fr.vernoux.ocaml) (2011, OCaml v3.12.0) despite its age and old OCaml version.

**Comment by Naereen** [comment]
And I got a reply from its author, the source code is no longer usable, and he recommends that if someone wants to build a native OCaml editor for Android (or iOS) they should start from scratch.

This really is something I would like to do, but it's also a very low priority, so I'll see in a few months.
